### ISSUE TITLE
Customer reports that there are conflicts when there is more than one plugin-embedded Brightcove Player within the same html document

### ISSUE THREAD

**Issue by vpitts** [prebid/videojs-mailonline-plugin#13]
If a Brightcove Player with an embedded plugin is put into an iframe, then the conflicts do not occur.  However, if the players are present within the same html document, there appears to be cross-contamination between the players.

Customer would prefer NOT to put their players into iframe.

**Comment by ynisman** [comment]
Implemented in version 1.3.10
