### ISSUE TITLE
How to specify MID or POST rolls (VAST)

### ISSUE THREAD

**Issue by josepowera** [prebid/videojs-mailonline-plugin#2]
Readme specifies that "this plugin supports midroll and postrolls ads in addition to preroll ads".

Do you have any example how to specify this?

**Comment by ynisman** [comment]
Hi,

If you look at the documentation that is provided on prebid.org for the Brightcode Prebid Plugin 
which describes the set of render options supported, you will see a description of the 'timeOffset' option:
http://prebid.org/dev-docs/plugins/bc/bc-prebid-plugin-render-options.html#timeOffset

You will notice that you can specify a mid-roll using a time value or a percent value. 
Post-roll is specified using the value 'end'.

This option should be included in a JSON object containing other options that are being passed to the plugin.
The plugin will pass all the rendering options to the MailOnline plugin.

Here is a sample of options which includes the 'timeOffset' for a mid-roll (at 10 minutes):
{
...
	"skippable": {
		"enabled": true,
		"videoThreshold": 15,
		"videoOffset": 5,
		"skipText": "Video can be skipped in %%TIME%% seconds",
		"skipButtonText": "SKIP"
	},
	"adStartTimeout": 5000,
	"timeOffset": "00:10:00",
	"adText": "Ad",
...
}
