### ISSUE TITLE
 v1.3.10 fires Console Error on Publisher site – MOL Error: "Failed to execute 'postMessage' on 'DOMWindow'"

### ISSUE THREAD

**Issue by graphicdeveloper** [prebid/videojs-mailonline-plugin#32]

**Comment by graphicdeveloper** [comment]
The following error shows that there is a problem with the origin setting on `postMessage` calls from the v1.3.10 Mail Online plugin:
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://acdn.adnxs.com') does not match the recipient window's origin ('http://www.lefigaro.fr').`

![postmessage_error](https://user-images.githubusercontent.com/453789/52509806-5f9ded00-2bae-11e9-9e37-009bca369f1b.png)

**Comment by ynisman** [comment]
Fix in version 1.3.11
