### ISSUE TITLE
is this support rendering adicon?

### ISSUE THREAD

**Issue by ttdriverhe** [prebid/videojs-mailonline-plugin#45]

**Comment by ttdriverhe** [comment]
Hi, do I need to do anything make the AdIcon get display? I followed the instructions, but my the AdIcon doesn't show up.

**Comment by vpitts** [comment]
The <AdIcon> node in VAST xml should be supported in the Brightcove Prebid Plugin as long as the xml contains a valid <AdIcon> node.  I am going to check with my test engineering team to make sure and to provide you with a sample xml that does work on our test pages.

Keep in mind that the plugin can use one of two rendering components:  MailOnline (associated with this repo) or Google IMA (default rendering component if you DFP is your primary ad server.  Do you know which rendering component you are using?  Do your options include dfpParameters?  Do you specify a value for the adRenderer option.

As soon as I get some info back from my test engineers, I will post it here.  It would also be helpful if you could provide a url to your xml that you are using to display ad icons.

**Comment by vpitts** [comment]
I did check with my test engineers - and they do see Ad Icons working as expected in both the Mail Online and the IMA ad renderers.  They are preparing a sample xml that you can try in your implementation - one that can be hit outside of our VPN.  I will post the url as soon as it is ready.

Again, if you provide us with your xml - we can take a look at it to see if we can determine what the problem may be.

**Comment by vpitts** [comment]
Here is a url that we use to demonstrate the rendering of an Ad Icon in our plugin:  https://video-demo.adnxs.net/encino/xml/Prebidmp4adicon.xml

I am waiting to get a screenshot from the test engineer showing the display of the ad icon

**Comment by vpitts** [comment]
<img width="1523" alt="Adicons_MOL" src="https://user-images.githubusercontent.com/13665689/78616262-9f9b4700-7828-11ea-95ad-12c11c49c090.png">
<img width="1512" alt="Adicons_IMA" src="https://user-images.githubusercontent.com/13665689/78616268-a3c76480-7828-11ea-8af7-64162313f071.png">
Here are two screenshots showing the Ad Icon being displayed by the plugin:  

- one using the MailOnline renderer
- the other using the IMA renderer

Let me know if you have any questions.  Also please share your xml so that we can see if there is an issue.

**Comment by vpitts** [comment]
My test engineer is seeing some problem with the xml I posted above when using the MailOnLine renderer plugin ... she is looking into that - I will let you know when we have fixed the xml.  But the xml does work in the IMA renderer

**Comment by vpitts** [comment]
<img width="620" alt="Screenshot-MOL" src="https://user-images.githubusercontent.com/13665689/78724488-6de6b680-78e2-11ea-820a-aef2d8e2d1fb.png">
<img width="635" alt="Screenshot-IMA" src="https://user-images.githubusercontent.com/13665689/78724513-78a14b80-78e2-11ea-816b-cb9990c02748.png">

Ok .. the xml is working now and here are the screenshots.  The first one is the xml running in the plugin using the MailOnLine renderer.  The second one is the same xml running in the plugin using the IMA renderer.  Notice that this xml just happens to specify two ad icons - one in the upper right corner and the second one in the lower right corner.  But whether you have one or more than one shouldn't make a difference.  

Let me know if you have your xml ready for us to try. Also let me know if you have any questions

**Comment by vpitts** [comment]
What is the VAST version of the xml you are trying to play?  This may be related to the issue you we're seeing.

**Comment by ttdriverhe** [comment]
Hi Vpitts, thank you very much for so much detailed explanation , yeah the ad icon works for staticResource, after read your code, I found it doesn't support type htmlResource and iframeResource. do you have any plan to support this two types? 

![image](https://user-images.githubusercontent.com/63136381/79299013-6db76e00-7f15-11ea-9a07-dea466aee421.png)

**Comment by ttdriverhe** [comment]
Beside this , there is a small issue. the imageType check imageTypes.indexOf(icon.creativeType)
should be imageTypes.indexOf(icon.creativeType) >= 0)

**Comment by vpitts** [comment]
Thanks @ttdriverhe  - we are working on a fix for this as well as for issue #47.  We will be doing some QA work next week and then should have an updated release after that.

**Comment by vpitts** [comment]
Version 1.3.18 of the MailOnline plugin has been released and published to the CDN:  https://acdn.adnxs.com/video/plugins/mol/videojs_5.vast.vpaid.min.js.

This release includes the new support for AdIcons, including HtmlResource and IFrameResource type icons.
