### ISSUE TITLE
Rendering AdIcon support for type HtmlResource and IframeResource 

### ISSUE THREAD

**Issue by ttdriverhe** [prebid/videojs-mailonline-plugin#47]
Hi Vpitts, after read the code, I found this plug doesn't support type htmlResource and iframeResource. do you have any plan to support this two types? thanks a lot!  😃

**Comment by ttdriverhe** [comment]
![image](https://user-images.githubusercontent.com/63136381/79299349-62187700-7f16-11ea-929d-554b3292e33f.png)

**Comment by ttdriverhe** [comment]
Beside this , there is a bug. the imageType check ```imageTypes.indexOf(icon.creativeType)```
should be ```imageTypes.indexOf(icon.creativeType) >= 0) ```

**Comment by ynisman** [comment]
We are working on support htmlResource and iframeResource right now.

**Comment by vpitts** [comment]
@ttdriverhe - we have a fix and are working on testing it.  I need to know how you use the plugin ... what browsers do you want to support?  do you embed the prebid plugin in the Brightcove Studio or do you embed it directly on the page?  I assume you are using this MailOnline plugin in conjunction with the Brightcove prebid plugin, correct?
This will help us test the correct set up.

**Comment by ttdriverhe** [comment]
Hi @vpitts  thank you so much for working on this feature.  Yeah,  I'm using the MailOnline with the Brightcove prebid plugin.  as for browsers, I think mainstream browsers are enough, such as Google Chrome, Firefox, Microsoft Edge etc.  thank you again, this is really helpful.

**Comment by vpitts** [comment]
@ttdriverhe - one last question - do you use Brightcove Studio to embed the prebid plugin or do you load the plugin directly on your page?  

Also if you have a test xml that we can include in our testing, that would be helpful.  Thanks.  
If you do not want to put the url here - you can email it directly to me at vikki.pitts@xandr.com

**Comment by ttdriverhe** [comment]
Hi @vpitts , I'm sorry, I don't quite understand how Brightcove plug works. But I believe we load the MailOnline plug directly on our page. I used the follow code directly on our html page.
`var vastAd = player.vastClient({
                        adTagUrl: "adTagUrl",
                        playAdAlways: true,
                        adCancelTimeout: 6000,
                        adsEnabled: true,
                        vpaidFlashLoaderPath: "../VPAIDFlash.swf"
                    });
`

I'm also sorry, i do not have a public test xml. but I believe as long as  the tested xml is following IAB standard, everything should be fine here.  thank you again! much appreciate! you are the king of JS 👍 . your plug helped me a lot.

**Comment by vpitts** [comment]
@ttdriverhe It looks from the code you posted that you are not using the prebid plugin.  It looks like you are calling the MailOnline plugin directly on your page.  If you were using the prebid plugin, the call to vastClient would be made internally by the plugin and you wouldn’t see that call directly on the page.
 
The prebid plugin is a plugin for the Brightcove player which will first run a prebid process to select the “best” ad to play.  Once the prebid process has completed, then the prebid plugin can use the MailOnline plugin to display the selected ad.  (The prebid plugin can alternately use the Google IMA plugin to render the ad, depending on the prebid configuration settings).  You can read more about the Prebid Plugin here:  http://prebid.org/dev-docs/plugins/index.html
 
This MailOnline plugin implementation was developed to be used with the prebid plugin.  While you can use it directly, independently of the prebid plugin, you may encounter behavior that we didn’t expect or code for.  Hopefully, things are working well for you so far using this MailOnline plugin implementation and you won’t encounter any unexpected behavior.  If you do, however, you may have to create your own fork to work around those issues.  We would be able to advise you if needed.
 
We are going to go forward with completing the support for Ad Icons regardless.  We will let you know once we release that code.  Let me know if all of this makes sense and whether you have any questions.

**Comment by ttdriverhe** [comment]
@vpitts  yes, I'm using MailOnline plugin directly. As for the rendering icon feature, I was copied your implementations to my project directly and that works great. I'm looking forward to the new release of Ad Icons.

**Comment by vpitts** [comment]
@ttdriverhe Glad to hear that the implementation is working great for you.  We should be able to make the release sometime next week.  I will definitely let you know when that happens.

**Comment by vpitts** [comment]
Version 1.3.18 of the MailOnline plugin has been released and published to the CDN:  https://acdn.adnxs.com/video/plugins/mol/videojs_5.vast.vpaid.min.js.

This release includes the new support for AdIcons, including HtmlResource and IFrameResource type icons.

**Comment by ttdriverhe** [comment]
Thanks you so much @vpitts
